projects:
  uber:
    schemaPath: >-
      C:/Users/CPU-MAJD/Desktop/workspace/Uber-driver-clone/Uber/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
